// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRTSioWTC5ttHu8_Xqb5omFTg5eQEQdxA',
    appId: '1:721364167186:web:8f9f061b9d9695c03c06cb',
    messagingSenderId: '721364167186',
    projectId: 'flutterfcm-8a0c4',
    authDomain: 'flutterfcm-8a0c4.firebaseapp.com',
    storageBucket: 'flutterfcm-8a0c4.appspot.com',
    measurementId: 'G-W3SJBHCFZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0SAjEFP5enzx803aptTsRfukczvtuRA4',
    appId: '1:721364167186:android:0ba452f72c0499f63c06cb',
    messagingSenderId: '721364167186',
    projectId: 'flutterfcm-8a0c4',
    storageBucket: 'flutterfcm-8a0c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClDuWbyneyobXG8Jtc9kQqNlZ5jJqfkfs',
    appId: '1:721364167186:ios:b96664171636eb173c06cb',
    messagingSenderId: '721364167186',
    projectId: 'flutterfcm-8a0c4',
    storageBucket: 'flutterfcm-8a0c4.appspot.com',
    iosBundleId: 'com.example.flutterFcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClDuWbyneyobXG8Jtc9kQqNlZ5jJqfkfs',
    appId: '1:721364167186:ios:278fec7beb0527f63c06cb',
    messagingSenderId: '721364167186',
    projectId: 'flutterfcm-8a0c4',
    storageBucket: 'flutterfcm-8a0c4.appspot.com',
    iosBundleId: 'com.example.flutterFcm.RunnerTests',
  );
}
